#!/bin/bash

ARRAY=( "WFCWOQEDHFCQEWOIHFCJOKIWEJSDCKDSCNOSCNKOSDCNWEUNFCSDCNIUDNCWENUINCJDNJCDCBWEHBRCHJBCJBEWJRVCBJEWVBEWVB" "dijauqshbdcijuqwsahudhqwuidhguiwqdhuiwq" "haqwsbdbicbxuqiw" "JDSFIUBDDSNJVNKSDNVJKSVGBNJ" "SDHJCBVSWDBCVWSEDVBN" )

echo "${ARRAY[$ARRAY%5]}"
